{{- if .Values.zabbixJavaGateway.enable }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.zabbixJavaGateway.service.annotations }}
  annotations:
    {{ toYaml .Values.zabbixJavaGateway.service.annotations | indent 4 }}
  {{- end }}
  name: {{ template "zabbix.javaGateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.zabbixJavaGateway.service.labels }}
    {{ toYaml .Values.zabbixJavaGateway.service.labels | indent 4 }}
    {{- end }}
    app: {{ include "zabbix.name" . | quote }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  {{- if .Values.zabbixJavaGateway.service.clusterIP }}
  clusterIP: {{ .Values.zabbixJavaGateway.service.clusterIP }}
  {{- end }}
  {{- if .Values.zabbixJavaGateway.service.externalIPs }}
  externalIPs:
    {{ toYaml .Values.zabbixJavaGateway.service.externalIPs | indent 4 }}
  {{- end }}
  {{- if .Values.zabbixJavaGateway.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.zabbixJavaGateway.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.zabbixJavaGateway.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $cidr := .Values.zabbixJavaGateway.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
    {{- end }}
  {{- end }}
  ports:
    - name: zabbix-jmx
      port: {{ .Values.zabbixJavaGateway.service.port }}
      protocol: TCP
      targetPort: {{ .Values.zabbixJavaGateway.service.targetPort }}
  selector:
    name: {{ template "zabbix.javaGateway.fullname" . }}
  type: {{ .Values.zabbixJavaGateway.service.type | quote }}
{{- end }}
